### PR TITLE
Incorrect mapping and merging of ModelUpdateResult

### LINKED ISSUE #28: Execution in a transaction does not get `success` property of the `ModelUpdateResult`
`ModelUpdateResult` has a mandatory `success` flag, but it seems absent in the return result from execution of a JSON Patch in a transactional `Executor` in the _ad hoc_ execution of a sequence of patches in a _Command Provider_:

```
root INFO Model Server (Node): Patch result:  {
  message: "Model '<path-to-resource-redacted>' successfully updated",
  patch: [
    {
      op: 'replace',
      path: '/whatever/0/bits/0/someReference/$ref',
      value: '_VKJUQY2ZEeyzFu-CyYmrIw'
    },
    { op: 'add', path: '/whatever/1/referencedThings/0/bit', value: [Object] },
    { op: 'remove', path: '/whatever/9/referencedThings/0/bit' }
  ]
}
```

The object also has a `message` property that isn't expected for a `ModelUpdateResult`, so it seems that the raw message from the _Model Server (Java)_ is returned instead of building a `ModelServerResult` from it.

(The log above is what I get when print the result from `const result = await executor.applyPatch(patch)`)

### PR DESCRIPTION
**Pull request by cdamus**
Fix the execution reply message in a transaction to correctly map the `message` to a `ModelUpdateResult`, then merge that.
Also merge the `success` and `patchModel` properties, in addition to the `patch` property.

Resolves #28.

Contributed on behalf of STMicroelectronics.

### CODE REVIEW

File: packages/modelserver-node/src/client/model-server-client.ts [hunk 1]
```diff
@@ -479,7 +479,7 @@ class DefaultTransactionContext implements TransactionContext {
         const result = WebSocketMessageAcceptor.promise<ModelUpdateResult>(this.socket, message => {
```
Comment (CamilleLetavernier) [inline packages/modelserver-node/src/client/model-server-client.ts:479]: If I read this correctly, the expected type of `result` here is ModelUpdateResult. However, WebSocketMessageAcceptor.promise() returns `message.data`, which contains a message and a patch (It isn't a "ModelUpdateResult").

The problem is that WebSocketMessageAcceptor.promise() takes a Predicate (it returns the raw message data if the Predicate is true, and undefined otherwise), whereas we need a Function (Because we need to convert the raw message data to a ModelUpdateResult - which may be successful or unsuccessful, but shouldn't be 'undefined').

**Review by CamilleLetavernier — CHANGES_REQUESTED** [review]
I think it only partially fixes the issue, as the Transaction's aggregated result should indeed be fixed now, but the sendExecuteMessage#result is still invalid

File: packages/modelserver-node/src/client/model-server-client.ts (hunk 1 above)
Comment (cdamus) [reply packages/modelserver-node/src/client/model-server-client.ts]: 🤦 Ah, yes, of course. The new commit e8ed4cbc8f42a53459d32320219205983ee26a5f addresses that.

**Review by CamilleLetavernier — APPROVED** [review]
Thanks for the fix, looks good to me!
