### PR TITLE
Fix early continuation after patch trigger

### LINKED ISSUE #7: Early continuation of transaction close with patch triggers
The implementation of the triggers provider registry aggregates multiple trigger providers into one. These are invoked in the context of a nested transaction. If one of the trigger providers provides a JSON patch and not a further nested transaction, then the patch is applied and the multi-trigger carries on.

However, in this case the multi-trigger continues before the upstream model server has applied the patch and replied with the result, so the root transaction ends up closing and there is no opportunity for the changes applied by the patch trigger to trigger further (recursive) changes.

The root cause of this is a missing `await` on the `applyPatch(...)` call in the multi-trigger to match the `await` of the `applyPatch(...)` in the `DefaultTransactionContext::performTriggers()` method.

### PR DESCRIPTION
**Pull request by cdamus**
- add the missing `await`
- add test coverage to check for early continuation
- avoid applying empty patches from triggers
- improve robustness of `DefaultTransactionContext::performTriggers`

Fixes #7.

Contributed on behalf of STMicroelectronics.

### CODE REVIEW

File: packages/modelserver-node/src/client/model-server-client.ts [hunk 1]
```diff
@@ -416,6 +416,10 @@ class DefaultTransactionContext implements TransactionContext {
             return Promise.reject('Socket is closed.');
         }
 
+        if (!patch || (Array.isArray(patch) && patch.length === 0)) {
+            return { success: false };
```
Comment (eneufeld) [inline packages/modelserver-node/src/client/model-server-client.ts:420]: why is it no success applying an empty patch?

**Review by eneufeld — APPROVED** [review]
Looks good. Thank you for fixing the bugs.

File: packages/modelserver-node/src/client/model-server-client.ts (hunk 1 above)
Comment (cdamus) [reply packages/modelserver-node/src/client/model-server-client.ts:420]: That's meant to signal to the caller that it was a nonsensical request. The server didn't attempt to apply the patch, so the patch was not successful.
